"""changed time to string

Revision ID: 496fb73b2bd5
Revises: 23ded26a31fc
Create Date: 2024-02-08 09:21:09.244428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496fb73b2bd5'
down_revision = '23ded26a31fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
