"""created event  table

Revision ID: 4a799dd9b63a
Revises: 7b62fbca1ee9
Create Date: 2024-02-05 22:21:48.071285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a799dd9b63a'
down_revision = '7b62fbca1ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.Integer(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Time', sa.Time(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Events')
    # ### end Alembic commands ###
