"""created guest  table

Revision ID: 7b62fbca1ee9
Revises: 0e21d5625203
Create Date: 2024-02-05 22:07:20.013642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b62fbca1ee9'
down_revision = '0e21d5625203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Integer(), nullable=True),
    sa.Column('Email', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    # ### end Alembic commands ###
